# Generated by Django 5.2.5 on 2026-01-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="image",
            field=models.ImageField(upload_to="static/images/"),
        ),
    ]
