# Generated by Django 5.2.5 on 2026-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_articles_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="image",
            field=models.ImageField(upload_to="images/articles/"),
        ),
    ]
