# Generated by Django 5.1.3 on 2025-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_userpostcomment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="share_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
