# Generated by Django 5.1.3 on 2025-07-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_share_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="share_token",
        ),
    ]
