# Generated by Django 5.1.3 on 2025-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
