# Generated by Django 5.1.3 on 2025-07-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address",
            new_name="location",
        ),
    ]
