# Generated by Django 5.1.3 on 2025-07-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userfcmtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
