# Generated by Django 5.2.5 on 2025-08-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lawn", "0001_initial"),
        ("plant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawnplant",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plant.plant"
            ),
        ),
        migrations.AddField(
            model_name="userlawn",
            name="lawn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lawn.lawn"
            ),
        ),
    ]
