# Generated by Django 5.1.3 on 2025-04-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lawn", "0001_initial"),
        ("plant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawnproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plant.product"
            ),
        ),
        migrations.AddField(
            model_name="userlawn",
            name="lawn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lawn.lawn"
            ),
        ),
    ]
