# Generated by Django 5.1.3 on 2025-11-19 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lawn", "0001_initial"),
        ("plant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lawnplant",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plant.plant"
            ),
        ),
        migrations.AddField(
            model_name="lawnplant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userlawn",
            name="lawn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lawn.lawn"
            ),
        ),
        migrations.AddField(
            model_name="userlawn",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
