# Generated by Django 5.1.3 on 2025-06-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawn", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawn",
            name="location",
            field=models.JSONField(default={"location": "qw3ererty"}),
            preserve_default=False,
        ),
    ]
