# Generated by Django 5.1.3 on 2025-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawn", "0004_lawn_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlawn",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
