# Generated by Django 5.2.5 on 2025-08-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lawn", "0004_lawnplant_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLawnPlant",
        ),
    ]
