# Generated by Django 5.1.3 on 2025-07-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lawn", "0005_userlawn_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lawn",
            name="location",
        ),
    ]
