# Generated by Django 5.1.3 on 2025-10-30 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=255)),
                ("image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SeasonalPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=255)),
                ("image", models.JSONField()),
                ("variety_info", models.CharField(max_length=200)),
                ("attributes", models.CharField(max_length=200)),
                ("family", models.CharField(max_length=500)),
                ("type", models.CharField(max_length=500)),
                ("native", models.CharField(max_length=500)),
                ("plant_dimension", models.CharField(max_length=500)),
                ("growth_stage", models.CharField(default="Seed", max_length=500)),
                ("days_to_maturity", models.CharField(max_length=200)),
                ("mature_speed", models.CharField(max_length=200)),
                ("mature_height", models.CharField(max_length=200)),
                ("fruit_size", models.CharField(max_length=200)),
                ("exposure", models.CharField(max_length=100)),
                (
                    "sunlight_requirement",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100, null=True)),
                ("soil_ph", models.CharField(blank=True, max_length=200, null=True)),
                ("hardiness", models.CharField(max_length=200)),
                (
                    "temperature_min",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "temperature_max",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "humidity_preference",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("watering_interval", models.CharField(max_length=202, null=True)),
                ("last_watered", models.DateField(blank=True, null=True)),
                ("next_watering_date", models.DateField(blank=True, null=True)),
                ("fertilizer_interval", models.CharField(max_length=202, null=True)),
                ("last_fertilized", models.DateField(blank=True, null=True)),
                ("next_fertilizing_date", models.DateField(blank=True, null=True)),
                ("trimming_interval", models.CharField(max_length=202, null=True)),
                ("last_trimmed", models.DateField(blank=True, null=True)),
                ("next_trimming_date", models.DateField(blank=True, null=True)),
                ("planted_date", models.DateField(blank=True, null=True)),
                ("health_status", models.CharField(default="Healthy", max_length=500)),
                ("common_pests", models.TextField(blank=True, null=True)),
                ("disease_signs", models.TextField(blank=True, null=True)),
                ("treatment_methods", models.TextField(blank=True, null=True)),
                (
                    "notification_send_date_and_type",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plant.category"
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plant.llm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant.plant",
                    ),
                ),
            ],
        ),
    ]
