# Generated by Django 5.1.3 on 2024-12-12 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=20)),
                ("image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=15)),
                ("image", models.CharField(max_length=255)),
                ("days_to_maturity", models.CharField(max_length=20)),
                ("mature_speed", models.CharField(max_length=20)),
                ("mature_height", models.CharField(max_length=20)),
                ("fruit_size", models.CharField(max_length=20)),
                ("family", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("native", models.CharField(max_length=50)),
                ("hardiness", models.CharField(max_length=200)),
                ("exposure", models.CharField(max_length=100)),
                ("plant_dimension", models.CharField(max_length=50)),
                ("variety_info", models.CharField(max_length=200)),
                ("attributes", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plant.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant.product",
                    ),
                ),
            ],
        ),
    ]
