# Generated by Django 5.2.5 on 2025-08-06 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=20)),
                ("image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=15)),
                ("image", models.JSONField()),
                ("days_to_maturity", models.CharField(max_length=20)),
                ("mature_speed", models.CharField(max_length=20)),
                ("mature_height", models.CharField(max_length=20)),
                ("fruit_size", models.CharField(max_length=20)),
                ("family", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("native", models.CharField(max_length=50)),
                ("hardiness", models.CharField(max_length=200)),
                ("exposure", models.CharField(max_length=100)),
                ("plant_dimension", models.CharField(max_length=50)),
                ("variety_info", models.CharField(max_length=200)),
                ("attributes", models.CharField(max_length=200)),
                ("planted_date", models.DateField(blank=True, null=True)),
                (
                    "fertilizer_interval",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_notification_send_date", models.JSONField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plant.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant.plant",
                    ),
                ),
            ],
        ),
    ]
