# Generated by Django 5.1.3 on 2025-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="health_status",
            field=models.CharField(blank=True, null=True),
        ),
    ]
