# Generated by Django 5.2.5 on 2025-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="last_notification_send_date",
            new_name="notification_send_date_and_type",
        ),
        migrations.AddField(
            model_name="plant",
            name="trimming_interval",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
