# Generated by Django 5.1.3 on 2025-11-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="common_pests",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="disease_signs",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="exposure",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="family",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="fertilizer_interval",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="growth_stage",
            field=models.CharField(default="Seed", max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="hardiness",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="health_status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="humidity_preference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="plant",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="native",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="notification_send_date_and_type",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_dimension",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="treatment_methods",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="trimming_interval",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="type",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="watering_interval",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
