# Generated by Django 5.1.3 on 2025-10-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_alter_plant_days_to_maturity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="days_to_maturity",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="plant",
            name="fertilizer_interval",
            field=models.CharField(max_length=202, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="fruit_size",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="plant",
            name="mature_height",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="plant",
            name="mature_speed",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="plant",
            name="notification_send_date_and_type",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="plant",
            name="trimming_interval",
            field=models.CharField(max_length=202, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="watering_interval",
            field=models.CharField(max_length=202, null=True),
        ),
    ]
