# Generated by Django 5.2.5 on 2026-01-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_alter_plant_health_status"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="season",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="season",
            name="to_date",
        ),
        migrations.AddField(
            model_name="plant",
            name="seasons",
            field=models.ManyToManyField(
                blank=True, related_name="plants", to="plant.season"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="attributes",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="days_to_maturity",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="exposure",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="family",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="fertilizer_interval",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="fruit_size",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="growth_stage",
            field=models.CharField(default="Seed", max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="hardiness",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="health_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="humidity_preference",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="mature_height",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="mature_speed",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="native",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_dimension",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="soil_ph",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="soil_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="sunlight_requirement",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="temperature_max",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="temperature_min",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="trimming_interval",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="variety_info",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plant",
            name="watering_interval",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plantregion",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plant.plant"
            ),
        ),
        migrations.AlterField(
            model_name="plantregion",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.region"
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="name",
            field=models.CharField(
                choices=[
                    ("winter", "Winter"),
                    ("spring", "Spring"),
                    ("summer", "Summer"),
                    ("fall", "Fall"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantregion",
            unique_together={("plant", "region")},
        ),
        migrations.DeleteModel(
            name="SeasonalPlant",
        ),
    ]
