# Generated by Django 5.1.3 on 2025-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0003_alter_plant_common_pests_alter_plant_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
