# Generated by Django 5.2.5 on 2026-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0003_remove_season_from_date_remove_season_to_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
