# Generated by Django 5.2.5 on 2025-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plant",
            "0003_rename_last_notification_send_date_plant_notification_send_date_and_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
