# Generated by Django 5.1.3 on 2025-10-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0003_alter_plant_days_to_maturity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="days_to_maturity",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="family",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="plant",
            name="fruit_size",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="growth_stage",
            field=models.CharField(default="Seed", max_length=500),
        ),
        migrations.AlterField(
            model_name="plant",
            name="health_status",
            field=models.CharField(default="Healthy", max_length=500),
        ),
        migrations.AlterField(
            model_name="plant",
            name="humidity_preference",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="mature_height",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="mature_speed",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="native",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_dimension",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="plant",
            name="soil_ph",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="temperature_max",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="temperature_min",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="type",
            field=models.CharField(max_length=500),
        ),
    ]
