# Generated by Django 5.2.5 on 2025-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0004_alter_plant_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
