# Generated by Django 5.2.5 on 2025-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0006_season_seasonalplant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="fertilizer_interval",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plant",
            name="notification_send_date_and_type",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="plant",
            name="trimming_interval",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
