# Generated by Django 5.1.3 on 2025-10-30 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FCMNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Watering", "Watering"),
                            ("Fertilizing", "Fertilizing"),
                            ("Pest Check", "Pest Check"),
                            ("Trimming", "Trimming"),
                            ("Seasonal Plant", "Seasonal Plant"),
                            ("Gardeninig Tip", "Gardeninig Tip"),
                            ("Seasonal Plant Suggestion", "Seasonal Plant Suggestion"),
                            ("Photo Prompt", "Photo Prompt"),
                            ("Morning in the Garden", "Morning in the Garden"),
                            ("Nature Break", "Nature Break"),
                            ("Touch of Green", "Touch of Green"),
                            ("Mindful Moment", "Mindful Moment"),
                            ("Tiny Care", "Tiny Care"),
                            ("Garden Vibes", "Garden Vibes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("sent", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
    ]
