# Generated by Django 5.2.5 on 2025-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FCMNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Watering", "Watering"),
                            ("Fertilizing", "Fertilizing"),
                            ("Pest Check", "Pest Check"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("sent", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
    ]
