# Generated by Django 5.2.5 on 2025-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Watering", "Watering"),
                    ("Fertilizing", "Fertilizing"),
                    ("Pest Check", "Pest Check"),
                    ("Trimming", "Trimming"),
                ],
                max_length=50,
            ),
        ),
    ]
