# Generated by Django 5.1.3 on 2025-08-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_fcmnotification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Watering", "Watering"),
                    ("Fertilizing", "Fertilizing"),
                    ("Pest Check", "Pest Check"),
                    ("Trimming", "Trimming"),
                    ("Seasonal Plant", "Seasonal Plant"),
                ],
                max_length=50,
            ),
        ),
    ]
