# Generated by Django 5.2.5 on 2025-08-13 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_fcmnotification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmnotification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
